routes:
  - name: completions
    route_type: llm/v1/completions
    model:
      provider: mosaicml
      name: mpt-7b-instruct
      config:
        mosaicml_api_key: $MOSAICML_API_KEY

  - name: embeddings
    route_type: llm/v1/embeddings
    model:
      provider: mosaicml
      name: instructor-xl
      config:
        mosaicml_api_key: $MOSAICML_API_KEY
