routes:
  - name: completions
    route_type: llm/v1/completions
    model:
      provider: clarifai
      name: mistral-7B-Instruct
      config:
        CLARIFAI_PAT: $CLARIFAI_PAT
        user_id: mistralai
        app_id: completion

  - name: embeddings
    route_type: llm/v1/embeddings
    model:
      provider: clarifai
      name: multimodal-clip-embed
      config:
        CLARIFAI_PAT: $CLARIFAI_PAT
        user_id: clarifai
        app_id: main