sudo: true
language: python

services:
  - docker

matrix:
  include:
    - stage: small
    - language: python
      python: 2.7
      install:
        - source ./install-travis-deps.sh
        - # Install protoc
        - wget https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip -O /travis-install/protoc.zip
        - sudo unzip /travis-install/protoc.zip -d /usr
      script:
        - ./run-small-tests.sh
        # Also run protobuf tests in the Python 2.7 small test runner
        - ./test-generate-protos.sh
    - language: python
      python: 3.6
      install:
        - source ./install-travis-deps.sh
      script:
        - ./run-small-tests.sh
    - language: r
      dist: trusty
      cache: packages
      before_install:
        - export NOT_CRAN=true
        - cd mlflow/R/mlflow
        - Rscript -e 'install.packages("devtools")'
        - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
        - cd ../../..
      install:
        - source ./install-travis-deps.sh
      script:
        - cd mlflow/R/mlflow
        - R CMD build .
        - R CMD check --no-build-vignettes --no-manual --no-tests mlflow*tar.gz
        - cd tests
        - export LINTR_COMMENT_BOT=false
        - Rscript ../.travis.R
      after_success:
        - export COVR_RUNNING=true
        - Rscript -e 'covr::codecov()'
    - language: java
      install:
        - source ./install-travis-deps.sh
      script:
        - cd mlflow/java
        - mvn clean package -q
    - language: node_js
      node_js:
        - "node" # Use latest NodeJS: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
      install:
      script:
        - cd mlflow/server/js
        - npm i
        - ./lint.sh
        - npm test -- --coverage
    - stage: large
    - language: python
      python: 2.7
      install:
        - source ./install-travis-deps.sh
      script:
        - ./run-large-tests.sh
    - language: python
      python: 3.6
      install:
        - source ./install-travis-deps.sh
      script:
        - ./run-large-tests.sh

if: false
