sudo: true

services:
  - docker

stages:
 - name: small
 - name: large
   if: type = cron OR branch = master OR commit_message =~ /^test-large/

matrix:
  include:
    - stage: small
    - python: 2.7
      install: ./install-travis-deps.sh
      script:
        - ./python-small.sh
    - python: 3.6
      install:  ./install-travis-deps.sh
      script:
        - ./python-small.sh
    - language: r
      dist: trusty
      cache: packages
      before_install:
        - export NOT_CRAN=true
        - cd mlflow/R/mlflow
        - Rscript -e 'install.packages("devtools")'
        - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
        - cd ../../..
      script:
        - cd mlflow/R/mlflow
        - R CMD build .
        - R CMD check --no-build-vignettes --no-manual --no-tests mlflow*tar.gz
        - cd tests
        - export LINTR_COMMENT_BOT=false
        - Rscript ../.travis.R
      after_success:
        - export COVR_RUNNING=true
        - Rscript -e 'covr::codecov()'
    - language: java
      script:
        - cd mlflow/java
        - mvn clean package -q
    - language: node_js
      node_js:
        - "node" # Use latest NodeJS: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
      install:
      script:
        - cd mlflow/server/js
        - npm i
        - ./lint.sh
        - npm test -- --coverage
    - stage: large
    - python: 2.7
      install: ./install-travis-deps.sh
      script:
        - ./python-large.sh
    - python: 3.6
      install:  ./install-travis-deps.sh
      script:
        - ./python-large.sh
