sudo: true

services:
  - docker

matrix:
  include:
    - language: python
      python: 2.7
      script:
        - sudo ./test-travis.sh
      install:
        - sudo ./install-travis.sh
    - language: python
      python: 3.6
      script:
        - sudo ./test-travis.sh
      install:
        - sudo ./install-travis.sh
    - language: r
      dist: trusty
      cache: packages
      env:
        global:
          - NOT_CRAN=true
            MLFLOW_TEST_REQUIREMENTS=false
      before_install:
        - sudo ./intall-travis.sh
      before_script:
        - cd R/mlflow
      after_failure:
        - cd tests
        - Rscript ../.travis.R
        - sleep 2
