sudo: true
language: python

services:
  - docker

jobs:
  include:
    - stage: small
      python:
        - '2.7'
        - '3.6'
      install:
        - ./install-travis-deps.sh
      script:
        - pytest --cov=mlflow --verbose --large --ignore=tests/h2o --ignore=tests/keras
          --ignore=tests/pytorch --ignore=tests/pyfunc --ignore=tests/sagemaker --ignore=tests/sklearn
          --ignore=tests/spark --ignore=tests/tensorflow
    - language: r
      dist: trusty
      cache: packages
      before_install:
        - export NOT_CRAN=true
        - cd mlflow/R/mlflow
        - Rscript -e 'install.packages("devtools")'
        - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
        - cd ../../..
      install:
        - ./install-travis-deps.sh
      script:
        - cd mlflow/R/mlflow
        - R CMD build .
        - R CMD check --no-build-vignettes --no-manual --no-tests mlflow*tar.gz
        - cd tests
        - export LINTR_COMMENT_BOT=false
        - Rscript ../.travis.R
      after_success:
        - export COVR_RUNNING=true
        - Rscript -e 'covr::codecov()'
    - language: java
      install:
        - ./install-travis-deps.sh
      script:
        - cd mlflow/java
        - mvn clean package -q
    - language: node_js
      node_js:
        - "node" # Use latest NodeJS: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
      install:
      script:
        - cd mlflow/server/js
        - npm i
        - ./lint.sh
        - npm test -- --coverage
    - stage: large
      python:
        - '2.7'
        - '3.6'
      install:
        - ./install-travis-deps.sh
      script:
        # TODO(czumar): Re-enable container building and associated SageMaker tests once the container
        # build process is no longer hanging
        # - SAGEMAKER_OUT=$(mktemp)
        # - if mlflow sagemaker build-and-push-container --no-push --mlflow-home . > $SAGEMAKER_OUT 2>&1; then
        #     echo "Sagemaker container build succeeded.";
        #   else
        #     echo "Sagemaker container build failed, output:";
        #     cat $SAGEMAKER_OUT;
        #   fi
        - pytest --cov=mlflow --verbose --large --ignore=tests/h2o --ignore=tests/keras
          --ignore=tests/pytorch --ignore=tests/pyfunc --ignore=tests/sagemaker --ignore=tests/sklearn
          --ignore=tests/spark --ignore=tests/tensorflow
        # Run ML framework tests in their own Python processes. TODO: find a better method of isolating
        # tests.
        - pytest --verbose tests/h2o --large
        # TODO(smurching): Re-enable Keras tests once they're no longer flaky
        # - pytest --verbose tests/keras --large
        - pytest --verbose tests/pytorch --large
        - pytest --verbose tests/pyfunc --large
        - pytest --verbose tests/sagemaker --large
        - pytest --verbose tests/sagemaker/mock --large
        - pytest --verbose tests/sklearn --large
        - pytest --verbose tests/spark --large
        - pytest --verbose tests/tensorflow --large

install: skip
script: skip
