[tool.black]
line-length = 100
target-version = ['py38']
force-exclude = '''
/(
    mlflow/protos/
  | mlflow/ml_package_versions\.py$
  | mlflow/pypi_package_index\.py$
  | tests/protos/
  | examples/recipes/
)
'''
