name: hyperopt_sklearn_example
channels:
  - defaults
dependencies:
  - python=2.7
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - matplotlib=2.2.2
  - pip:
    - mlflow
    - hpsklearn

