name: hyperparam_example
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip=20.0.2
  - numpy==1.14.3
  - click
  - pip:
    - pandas==0.22.0
    - scipy
    - scikit-learn==0.19.1
    - matplotlib==2.2.2
    - keras==2.2.2
    - mlflow>=1.0
    - Gpy==1.9.2
    - GpyOpt==1.2.5
    - pyDOE==0.3.8
    - hyperopt==0.1
