channels:
- defaults
- conda-forge
- pytorch
dependencies:
- python=3.8.2
- pytorch>=1.7.1
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - boto3
  - pandas
  - captum
  - sklearn
  - prettytable
  - torchtext
