channels:
- conda-forge
dependencies:
- python=3.8.12
- pip
- pip:
  - mlflow
  - mypy-extensions==0.4.3
  - pandas==1.3.4
  - scikit-learn==0.24.2
  - typing-extensions==4.0.0
  - xgboost==1.5.0
name: mlflow-env
