name: 'update-requirements'
description: 'Update requirements.yaml'

inputs:
  requirements-yaml-location:
    description: 'Local file path of the requirements.yaml specification'
    required: true
  requirements-txt-output-location:
    description: 'Local output path for the generated requirements.txt file'
    required: true

outputs:
  updated:
    description: 'Indicates whether the requirements have been updated'
    value: ${{ steps.update-requirements.outputs.updated }}

runs:
  using: 'composite'
  steps:
    - name: Update requirements
      id: update-requirements
      shell: bash --noprofile --norc -exo pipefail {0}
      run: |
        python dev/update_requirements.py --requirements-yaml-location ${{ inputs.requirements-yaml-location }}
        if [ -z "$(git status --porcelain)" ]; then
          echo "::set-output name=updated::false"
        else
          python dev/generate_requirements.py \
            --requirements-yaml-location ${{ inputs.requirements-yaml-location }} \
            --requirements-txt-output-location ${{ inputs.requirements-txt-output-location }}
          git diff --color=always
          echo "::set-output name=updated::true"
        fi
