[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "clint"
description = "A custom linter to enforce rules that ruff doesn't support."
version = "0.1.0"
authors = [{ name = "mlflow", email = "mlflow@mlflow.com" }]
dependencies = ["tomli"]

[tool.setuptools]
package-dir = { "" = "src" }

[project.scripts]
clint = "clint:main"
