name: pytorch_example
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - torch==1.8.1
    - torchvision==0.9.1
    - mlflow>=1.0
    - tensorboardX
    - protobuf<=3.20.1 #Remove once PTL supports latest protobuf - https://github.com/PyTorchLightning/pytorch-lightning/issues/13212
