channels:
- conda-forge
dependencies:
- python=3.8.2
- pip
- pip:
  - mlflow
  - torch==1.8.0
  - torchvision==0.9.1
  # Avoid using torchmetrics 0.6.0 due to https://github.com/PyTorchLightning/pytorch-lightning/discussions/10253
  - torchmetrics!=0.6.0
  - pytorch-lightning==1.0.2
