name: CircleCI artifacts redirector

on: [status]
jobs:
  main:
    if: "github.event.context == 'ci/circleci: build_doc'"
    runs-on: ubuntu-latest
    steps:
      - uses: larsoner/circleci-artifacts-redirector-action@0.3
        id: create-link
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/docs/build/html/index.html
          circleci-jobs: build_doc
          job-title: Preview docs on CircleCI
      - name: Check URL
        run: |
          curl --fail ${{ steps.create-link.outputs.url }}
