name: Patch

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  labeling:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/patch.js');
            await script({ github, context, core });
