# A workflow to validate at least one release-note category is selected

name: Release-note category

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  main:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: validate-labeled
        uses: actions/github-script@v6
        if: ${{ github.event.action != 'closed' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // https://github.com/actions/github-script#run-a-separate-file
            const script = require("./.github/workflows/release-note-category.js");
            await script({ core, context, github });

      - name: post-merge
        uses: actions/github-script@v6
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // https://github.com/actions/github-script#run-a-separate-file
            const script = require("./.github/workflows/release-note-category.js");
            await script.postMerge({ core, context, github });
