name: Requirements

on:
  pull_request:
    paths:
      - requirements/core-requirements.yaml
      - requirements/skinny-requirements.yaml
  schedule:
    - cron: '0 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  MLFLOW_CONDA_HOME: /usr/share/miniconda
  SPARK_LOCAL_IP: localhost
  # Best effort to test MLflow with newer versions of dependencies and increase
  # the maximum supported major versions. For example, pandas > 1.3 is not installable
  # in Python 3.7, but it is in Python 3.8.
  PYTHON_VERSION: '3.8'

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  skinny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
      - name: Install dependencies
        run: |
          source ./dev/install-common-deps.sh --skinny
      - name: Run tests
        run: |
          ./dev/run-python-skinny-tests.sh

  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: ./.github/actions/setup-pyenv
      - uses: ./.github/actions/setup-java
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
      - name: Install dependencies
        run: |
          source ./dev/install-common-deps.sh --ml
      - name: Run tests
        run: |
          source dev/setup-ssh.sh
          ./dev/run-python-tests.sh

  create-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs: [skinny, core]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dev script dependencies
        run: |
          pip install -r dev/requirements.txt
      - uses: ./.github/actions/update-requirements
      - name: Create PR branch name
        id: pr-branch
        run: |
          echo "::set-output name=name::update-requirements-$(git diff | sha256sum | head -c 8)"
      - uses: actions/github-script@v6
        id: pr-exists
        with:
          result-encoding: string
          script: |
            const recentPrs = await github.rest.pulls.list({
              owner: 'mlflow',
              repo: 'mlflow',
              per_page: 100,
              sort: 'created',
              direction: 'desc',
            });
            const exists = recentPrs.data.some(
              pr => pr.head.ref === '${{ steps.pr-branch.outputs.name }}'
            );
            return exists.toString();
      # If there are no changes, the create-pull-request action exits silently
      - uses: peter-evans/create-pull-request@v4
        if: steps.pr-exists.outputs.result != 'true'
        with:
          token: ${{ secrets.MLFLOW_AUTOMATION_TOKEN }}
          add-paths: requirements
          commit-message: 'Update requirements'
          signoff: true
          committer: 'mlflow-automation <mlflow-automation@users.noreply.github.com>'
          author: 'mlflow-automation <mlflow-automation@users.noreply.github.com>'
          branch: ${{ steps.pr-branch.outputs.name }}
          title: 'Update requirements'
          body: |
            Build Log: https://github.com/mlflow/mlflow/actions/runs/${{ github.run_id }}
