name: sklearn

# A cron job to ensure autologging works properly in older versions of scikit-learn

on:
  schedule:
    # Run this action daily at 7:00 UTC
    - cron: "0 7 * * *"
  pull_request:
    branches:
      - master
    paths:
      - mlflow/sklearn/**

jobs:
  sklearn:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "0.19.2"
          # unsupported versions
          # --------------------
          # supported versions
          - "0.20.3"
          - "0.21.2"
          - "0.22.2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r dev/small-requirements.txt
      - name: Update scikit-learn
        run: |
          pip install scikit-learn==${{ matrix.version }}
      - name: Check version
        id: version
        env:
          COMMAND: >
            from mlflow.sklearn.utils import _is_supported_version;
            supported = _is_supported_version();
            print('::set-output name=supported::{}'.format(str(supported).lower()));
        run: |
          python -c "$COMMAND"
      - name: Run tests
        id: tests
        continue-on-error: ${{ steps.version.outputs.supported != 'true' }}
        run: |
          # Disable fast-fail otherwise this step would exit right after the pytest command fails
          set +e

          pytest --verbose tests/sklearn/test_sklearn_autolog.py --large
          failed=$([ $? -ne 0 ] && echo "true" || echo "false")
          echo "::set-output name=failed::${failed}'"

      - name: Warn
        if: ${{ steps.version.outputs.supported == 'true' && steps.tests.outputs.failed == 'true' }}
        run: |
          echo "::warning ::Tests failed on an unsupported scikit-learn version"
