name: sklearn

# DELETE THIS FILE LATER

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sklearn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["0.20.3", "0.23.2"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
        run: |
          source ./dev/install-common-deps.sh
          pip install -e .
          pip install sklearn==${{ matrix.version }}
      - name: Run tests
        run: |
          pytest --verbose tests/sklearn
