name: Store wheel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Build UI
      working-directory: mlflow/server/js
      env:
        CI: false
      run: |
        npm install
        npm run build
    - name: Build wheel
      id: build-wheel
      run: |
        pip install wheel
        python setup.py bdist_wheel
        echo "::set-output name=wheel-path::$(find dist -type f)"

    - uses: actions/upload-artifact@v2
      if: github.event_name != 'push'
      with:
        name: wheel.zip
        path: ${{ steps.build-wheel.outputs.wheel-path }}
