name: Maintainer approval for requirement edits

on:
  pull_request:
    paths:
      - setup.py
      - requirements/skinny-requirements.yaml

permissions:
  pull-requests: write

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail without core maintainer approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(context.payload.pull_request, null, 2))

            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/require-core-maintainer-approval.js`);
            const reason = (
              "Editing requirements files can cause conflicts in downstream processes " +
              "that depend on MLflow. Please ensure that one of the MLflow Core Maintainers " +
              "has a chance to review this PR."
            );
            await script({ context, github, core, reason });
