name: Require core maintainer approval when editing requirements

on:
  pull_request:
    paths:
      - setup.py
      - requirements/skinny-requirements.yaml

permissions:
  contents: read
  pull-requests: write

jobs:
  warn:
    runs-on: ubuntu-latest
    steps:
      - name: Fail without core maintainer approval
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/require-core-maintainer-approval.js`);
            script({ context, github, core });
